# Copyright 2015 Adobe
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)
# Based on a version by Louis Dionne

shallow_clone: true

image:
  - Visual Studio 2017

build:
  verbosity: detailed

configuration:
  - Debug
platform:
  - x64

branches:
  except:
    - /pr\/.+/

install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - mkdir C:\projects\deps
  - cd C:\projects\deps


  ############################################################################
  # Install a recent CMake
  ############################################################################
  # - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-win64-x64.zip"
  # - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  # - 7z x cmake.zip -oC:\projects\deps > nul
  # - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  # - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

build_script:
  - cd C:\projects\libraries
  - IF EXIST build RMDIR /S /Q build
  - MKDIR build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -D BOOST_ROOT=C:/Libraries/boost_1_69_0 -D CMAKE_BUILD_TYPE=debug -D Boost_USE_STATIC_LIBS=ON ..
  - cmake --build . --config Release
  - ctest -C Release 
  
